language: android

os: linux
dist: precise
sudo: required
addons:
  apt:
    sources:
      # https://github.com/bazelbuild/bazel/issues/1821#issuecomment-262870638
      - sourceline: "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8"
        key_url: "https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg"
      - ubuntu-toolchain-r-test
    packages:
      - oracle-java8-installer
      - libstdc++-4.9-dev # https://github.com/nodegit/nodegit/issues/853
      - bazel=0.4.5

jdk:
  - &jdk_for_publishing oraclejdk8

android:
  components:
    - tools
    - tools # Duplicated as per https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - build-tools-25.0.2
    - android-25
    - platform-tools
    - extra-android-m2repository

before_install:
  - sudo rm -f /etc/mavenrc
  - wget http://www.us.apache.org/dist/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz
  - tar -zxvf apache-maven-3.1.1-bin.tar.gz
  - export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=192m"
  - export M2_HOME=$PWD/apache-maven-3.1.1
  - export PATH=$M2_HOME/bin:$PATH
  - mvn --version

script: bazel test --test_output errors //...

env:
  global:
    - secure: eGc3LHBRIPmTnXLM1YoIqG1do9BkpFI2pJm3fz5Cd8UaXtf7Oefa+Ts3rcn4ipee5A+lf8kEouPshSoaQs81KZ2/qf8rSTCIqeFjHR8hzmOVYo/0zRfS/VSUT0yqN+jeRhuNk3+A49RTPlcfJqPv3tyddtrM1vF7axhCJPQIRJM=
    - secure: LTzrlqcSNeZTOV52D3ibY9RBdxY4Yu8dUOYhAonrWLE+eDTzuoyCzcPw8pEcYVNUi1rG6Q7v3QBDTnBztsPoCbcN5tEGjw5cQEbfEzSTkWaNCFjncWn36cLwx9lgbF+5Db/L0mYJ36unDKUpKVC8AgOtxQibfv/ffugfxxj8ohY=
    - secure: PEdRiHTy+xVFPnlBwOhr7RVW/QIFSgd4hO0LESRBeF7KGIjxTZWtKPjnYrysZFm6tozMk6WBVJO6avOss0v7L64nemwpCnSspNYBa6pRGPgQ3rv/wgdPSzqDDmABmpPC18EHbUtF94KVdRX3Cr4kmwKQyD+YUKNRCY11Txt+xfo=
    - JDK_FOR_PUBLISHING: *jdk_for_publishing

after_success:
  - util/generate-latest-docs.sh
  - util/publish-snapshot-on-commit.sh

branches:
  only:
    - master
    - /^release.*$/

cache:
  directories:
    - $HOME/.cache/bazel
